apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: pass-in-api
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/tmanso9/pass-in-api.git
    targetRevision: HEAD
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: pass-in
  syncPolicy:
    automated:
      prune: true