version: '3.8'

services:

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-pass-in
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - pass-in
    volumes:
      - 'db:/var/lib/postgresql/data'

  api-pass-in:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-pass-in
    ports:
      - ${PORT}:3000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - PORT=${PORT}
    depends_on:
      - postgres
    networks:
      - pass-in
  
networks:
  pass-in:
    driver: bridge

volumes:
  db: 